### ISSUE TITLE
Bug: 无法使用postgresql

### ISSUE THREAD

**Issue by eya46** [he0119/nonebot-plugin-user#159]
### 描述问题

执行初次迁移后报错:

```
sqlalchemy.exc.IdentifierError: Identifier 'fk_nonebot_plugin_user_bind_original_id_nonebot_plugin_user_user' exceeds maximum length of 63 characters
```

查了下，说是关系名太长了导致的

https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
### 复现步骤

先这样，再这样，接着那样
```.env
SQLALCHEMY_DATABASE_URL="postgresql+asyncpg://postgres:114514@127.0.0.1:5432/db"
```

![c181b73adeeb57ddac9864a7ee56e2f3](https://github.com/user-attachments/assets/91523a70-6f52-4698-9c93-d3bd7148d9b2)
![30b6f4901da87c7db536b1291fda5f72](https://github.com/user-attachments/assets/e12e0c61-0b90-402e-9a28-a908709cb391)

![d9700eee070d0dd953b778d6a9b26265](https://github.com/user-attachments/assets/bbd9a949-6cc0-422b-af90-870aba3748f6)

**Comment by he0119** [comment]
看来还得改一下迁移脚本，之前其实已经把外键删除了。

**Comment by eya46** [comment]
试了下fix/foreignkey分支用的ValueError抓不住sqlalchemy.exc.IdentifierError

**Comment by he0119** [comment]
居然，SQLite 上是 ValueError，我还以为其他数据库也是一样的。
